# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDetails',
            new_name='BookDetail',
        ),
    ]
