# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BookCategory',
        ),
        migrations.RenameModel(
            old_name='CategoryImage',
            new_name='BookCategoryImage',
        ),
        migrations.RenameModel(
            old_name='BookDetails',
            new_name='BookDetail',
        ),
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='BookMainCategory',
        ),
    ]
