# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170113_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BookCategory',
        ),
        migrations.RenameModel(
            old_name='CategoryImage',
            new_name='BookCategoryImage',
        ),
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='BookMainCategory',
        ),
    ]
