# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='student_enrolled',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
