# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprovider',
            old_name='courseprovider_name',
            new_name='course_provider',
        ),
    ]
