# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='student_enrolled',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
