# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20170115_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_provider', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.CourseProvider'),
        ),
    ]
