# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 16:32
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('myproject', '0002_course_detail_student_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
