# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20170122_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprovider',
            old_name='course_provider',
            new_name='course_provider_name',
        ),
    ]
