# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20170122_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='full name')),
            ],
            options={
                'verbose_name': 'subscription',
                'abstract': False,
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
