# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 13:27
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_auto_20170108_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='description',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
