# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_auto_20170224_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_detail',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='course_detail',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 24, 18, 57, 18, 230843, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
