# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_auto_20170318_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='media_root/course/'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(upload_to='media_root/course/'),
        ),
    ]
