# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
